#pragma once
#include <pebble.h>

// #define MODEL_COUNT 9
#define SETTINGS_KEY 125

typedef struct ClaySettings {
  //bool EnableSecondsHand;
  //bool EnableSecondsAlways;
  //int SecondsVisibleTime;
  char PosLeft[4];
  char PosRight[4];
  char PosTop[4];
  char PosBottom[4];
  bool EnableDate;
  bool EnableBattery;
  bool EnableBatteryLine;
  bool EnableLogo;
  char LogoText[18];
  bool VibeOn;
  bool AddZero12h;
  bool RemoveZero24h;
  bool showlocalAMPM;
  bool showMinorTick;
  bool showMajorTick;
  bool DigitalHour;
  bool SmoothMinuteHand;
  int MinuteHandUpdateIntervalSec;
  bool OrbitComplications;
  bool EnableAlarmCalendarSync;
  GColor SyncedAlarmPinColor;
  GColor CalendarPinColor;
  int Font;
  int CentreSize;
  int InnerCentreSize;
  int HandThickness;
  int BackSize;
  int BackLen;
  char _BWThemeSelect[4];
  char ThemeSelect[4];
  GColor BackgroundColor1;
  GColor ComplicationBorderColor;
  GColor ComplicationShadowColor;
  GColor MinuteHandShadowColor;
  GColor TextColor1;
  GColor MinorTickColor;
  GColor TextColor3;
  GColor MajorTickColor;
  GColor DateColor;
  GColor _BWDateColor;
  GColor HourDigitsColor;
  GColor HoursHandBorderColor;
  GColor MinutesHandColor;
  GColor MinutesHandBorderColor;
  GColor SecondsHandColor;
  GColor BatteryLineColor;
  GColor _BWBackgroundColor1;
  GColor _BWMinuteHandShadowColor;
  GColor _BWMinHandBatLineColor;
  GColor _BWHourDigitsColor;
  GColor _BWMajorTickColor;
  GColor BTQTColor;
  GColor _BWBTQTColor;
  bool BWShadowOn;
  bool ShadowOn;
  bool ForegroundShape;
  int ComplicationFontSizeAdj;
  bool TimelineAlarmPin;
  bool TimelineTimerPin;
  bool ShowWatchDialWindow;
  GColor WatchDialWindowColor;
  GColor MinimizedMajorTickColor;
  GColor ComplicationBackgroundColor;
  GColor LocalAlarmPinColor;
} __attribute__((__packed__)) ClaySettings;

typedef struct {
  char name[4];
  GColor BackgroundColor1;
  GColor ComplicationBorderColor;
  GColor ComplicationBackgroundColor;
  GColor ComplicationShadowColor;
  GColor DateColor;
  GColor HourDigitsColor;
  GColor MinutesHandColor;
  GColor MinuteHandShadowColor;
  GColor MajorTickColor;
  GColor MinimizedMajorTickColor;
  GColor MinorTickColor;
  GColor BatteryLineColor;
  GColor BTQTColor;
  GColor LocalAlarmPinColor;
  GColor SyncedAlarmPinColor;
  GColor CalendarPinColor;
  GColor WatchDialWindowColor;
} ThemePreset;